/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#define USE_GLOBAL_H

#include "Header_USER.h" /* Header_USER.h 포함 */

IfxCpu_syncEvent g_cpuSyncEvent = 0;

float a;

void delay(uint32 delayTime){

    for (volatile uint32 i = 0; i < delayTime; i++) {

    }
}

void delay_High(uint32 delayTime){

    for (volatile uint32 i = 0; i < delayTime; i++) {
        IfxPort_setPinHigh(&MODULE_P10,2);
    }
}

void delay_Low(uint32 delayTime){

    for (volatile uint32 i = 0; i < delayTime; i++) {
        IfxPort_setPinLow(&MODULE_P10,2);
    }
}



void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /*1. GPIO 초기화 함수 추가*/
    init_GPIO();

        
    while(1)
    {
        /* 2-1. GPIO PORT__005 핀 Low로 설정(LiteKit)*/
        /* 2-2. GPIO PORT__005 핀 High로 설정(ShieldBuddy)*/
        IfxPort_togglePin(&MODULE_P10,2);
        //IfxPort_setPinHigh(&MODULE_P10,2);
        //IfxPort_setPinLow(&MODULE_P10,2);
        //delay_High(5000000);
        //delay_Low(5000000);
        delay(5000000*a);

        if(1<a)
        {
            a=0;
//            IfxPort_togglePin(&MODULE_P10,2);
        }

       a+=0.01;
    }
}
